import { gql } from "@apollo/client";
import Head from "next/head";
import Image from "next/image";
import client from "../../client";
import styles from "../../styles/Home.module.css";

const GET_ITEM = gql`
  query GetItem($itemId: String!) {
    item(id: $itemId) {
      id
      title
      url
    }
  }
`;

const GET_ITEMS_ID = gql`
  query {
    items {
      id
    }
  }
`;

export default function ItemPage({ item }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{item.title}</h1>
        <h3>{item.url}</h3>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticPaths() {
  const { data } = await client.query({ query: GET_ITEMS_ID });
  const paths = data.items.map((item) => ({ params: { id: item.id } }));

  return { paths, fallback: false };
}

export async function getStaticProps({ params }) {
  const { data } = await client.query({
    query: GET_ITEM,
    variables: { itemId: params.id },
  });

  return {
    props: { item: data.item },
  };
}
